# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arma_colSums <- function(x) {
    .Call('_Bayesprofiling_Arma_colSums', PACKAGE = 'Bayesprofiling', x)
}

Arma_colmax <- function(x) {
    .Call('_Bayesprofiling_Arma_colmax', PACKAGE = 'Bayesprofiling', x)
}

Arma_colmean <- function(x) {
    .Call('_Bayesprofiling_Arma_colmean', PACKAGE = 'Bayesprofiling', x)
}

Arma_rowSums <- function(x) {
    .Call('_Bayesprofiling_Arma_rowSums', PACKAGE = 'Bayesprofiling', x)
}

Arma_rowmax <- function(x) {
    .Call('_Bayesprofiling_Arma_rowmax', PACKAGE = 'Bayesprofiling', x)
}

Arma_rowmean <- function(x) {
    .Call('_Bayesprofiling_Arma_rowmean', PACKAGE = 'Bayesprofiling', x)
}

dmvn <- function(x, mu, cov, logd = FALSE) {
    .Call('_Bayesprofiling_dmvn', PACKAGE = 'Bayesprofiling', x, mu, cov, logd)
}

